url: https://ammimarketic.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: AMMI MarkeTIC
email: abdoulayedoucoure.ammi@gmail.com
description: "VOTRE AGENCE MARKETING avec une équipe d’experts spécialisée dans le web et l’IA. Obtenez une présence digitale complète - Simple et Rapide ! Nos délais de livraison d'une semaine par étape peuvent être accélérés à votre demande."


# Team names, titles and social links
people:
- name: WELTARE Strategies
  pic: 1
  position: Conseil en strategie
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Ethercourt Machine Learning
  pic: 2
  position: Conseil en IA
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Votre entreprise
  pic: 3
  position: Services aux entreprises
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AmmiMarketic
  - title: facebook
    url: https://www.facebook.com/ammimarketic
  - title: linkedin
    url: https://www.linkedin.com/showcase/ammi-marketic
  - title: github
    url:  https://github.com/AMMIMarkeTIC
  

# Postal address (add as many lines as necessary)
address:
  - line: BKO
  - line: PAR

# Build settings
markdown: kramdown
permalink: pretty
